describe('studio functionality', () => {
  it('visits a basic html page', () => {
    cy.visit('cypress/e2e/index.html')

    // create a long test by generating a lot of cy.log commands
    // (We're purposely not using a for loop so the test is long when shown in the cloud studio panel)
    cy.log('log 1')
    cy.log('log 2')
    cy.log('log 3')
    cy.log('log 4')
    cy.log('log 5')
    cy.log('log 6')
    cy.log('log 7')
    cy.log('log 8')
    cy.log('log 9')
    cy.log('log 10')
    cy.log('log 11')
    cy.log('log 12')
    cy.log('log 13')
    cy.log('log 14')
    cy.log('log 15')
    cy.log('log 16')
    cy.log('log 17')
    cy.log('log 18')
    cy.log('log 19')
    cy.log('log 20')
    cy.log('log 21')
    cy.log('log 22')
    cy.log('log 23')
    cy.log('log 24')
    cy.log('log 25')
    cy.log('log 26')
    cy.log('log 27')
    cy.log('log 28')
    cy.log('log 29')
    cy.log('log 30')
    cy.log('log 31')
    cy.log('log 32')
    cy.log('log 33')
    cy.log('log 34')
    cy.log('log 35')
    cy.log('log 36')
    cy.log('log 37')
    cy.log('log 38')
    cy.log('log 39')
    cy.log('log 40')
    cy.log('log 41')
    cy.log('log 42')
    cy.log('log 43')
    cy.log('log 44')
    cy.log('log 45')
    cy.log('log 46')
    cy.log('log 47')
    cy.log('log 48')
    cy.log('log 49')
    cy.log('log 50')
  })
})
